[package]
name = "chip8-wasm"
version = "0.1.0"
authors = ["Lorenzo Allotta <lorenzo.allotta@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.50"
rand = "0.7.0"